addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"   % "3.9.5")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"        % "2.0.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"        % "1.0.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release" % "1.5.5")
